name: Node.js CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm run test:unit
      env:
        NODE_ENV: test
        JWT_SECRET: test-secret
        DATABASE_URI: mongodb://localhost:27017/test_db
        EMAIL_FROM: test@example.com

    - name: Run integration tests
      run: npm run test:integration
      env:
        NODE_ENV: test
        JWT_SECRET: test-secret
        DATABASE_URI: mongodb://localhost:27017/test_db
        EMAIL_FROM: test@example.com

    - name: Run full test suite
      run: npm test
      env:
        NODE_ENV: test
        JWT_SECRET: test-secret
        DATABASE_URI: mongodb://localhost:27017/test_db
        EMAIL_FROM: test@example.com

